export default {
    LOGIC_ERROR: 'LOGIC_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    REQUIRED: 'REQUIRED',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_LENGTH: 'INVALID_LENGTH',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_NOT_ACTIVE: 'TOKEN_NOT_ACTIVE',
    TOKEN_ERROR: 'TOKEN_ERROR',
    DESTROYED_TOKEN: 'DESTROYED_TOKEN',
};
