export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const SINGUP_SUCCESS = "SINGUP_SUCCESS";
export const SINGUP_FAILURE = "SINGUP_FAILURE";
export const ADD_POSITIONS = "ADD_POSITIONS";
export const ADD_WOKERS = "ADD_WOKERS";
